NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.icici.bankconsortiumbcnet.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.icici.bankconsortiumbcnet.com-cert.pem
    OrganizationalUnitIdentifier: peer
